name: Nix flake

on:
  push:
  pull_request:

jobs:
  flake:
    name: Build Nix flake
    runs-on: docker
    container: nixos/nix
    env:
      NIX_CONFIG: "experimental-features = nix-command flakes"
    steps:
      - run: |
          git clone --recurse-submodules "${FORGEJO_SERVER_URL}/${FORGEJO_REPOSITORY}" .
          git checkout "${FORGEJO_SHA}"
      - run: nix build . -L
